sudo: false

language: go
go:
- '1.12'

env:
- GO111MODULE=on
- DOCKER_USERNAME="opensource@postfinance.ch"
- secure: jJUR0jG9XLSdw2JQGq1+oIkvi30ST3Epc31h+Gwf3DvBwKoCE3xZu54DG3HXHMV6dlz9fRNQVWm7AF9rGWBO6hk+u17R5AIdjYJMNYEU9eybgLAAljq8vricH6+uIC77It9FFCwyv2l1zv2fGNummMbqBnJhfIxf+39n+gEBUyrXivoVp8e9ZTwQ8mNuwCd0M1fq6qQKYhYOf5+z0OeRigvv/ZaHF3iRKntllwlUUWrO3DifYuJrt/6ieO41TkEfZD7awEeSHxxQ9gKsTczZ+vwJsY+XcVpM8TuZXXgL56ZmtLow2f5+MQjj+TcmF6etnUVUh2bUjDXUPgZD/TCcS1tXxYm4sQJPIWChF1YpbE0mwQ2e/KcZAD/lcUkp56IyzuaChoNPmiiYL+vk9HSSV/jgxALwwk3DdvX8h0s2i6UkTkjrOj8/ls1i/x83WIqZHOZUmCbfPQaH8ntXTAASijh7YDl/PKMxTLEDWRJbTmEL7AG3JXAPFzj3wt/9UOeRDxOtTMoQYU3UfBzkHHALji/eCHEgtWZMsijp8sJd/kAwdEzVwtwpsQ19+HG/NSxzrdB+ToBlXJ/Oh8vTPe5B64Qc0aQff5Q0x4VuNliywCHbLhCcJmnPDGcuRELV6iNLfkV3RzbMun+gP+G5q4c2jorirZfWGcJYiTTaImbqJzg=
- DOCKER_TAG="latest"


services:
- docker

stages:
- build

before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- TAG=$(git describe --tags --abbrev=0)
- COUNT=$(git rev-list --count ${TAG}...HEAD)
- test ${COUNT} -eq 0 && export DOCKER_TAG=$(echo ${TAG} | sed 's/^v//')

jobs:
  include:
  - stage: build
    name: "build and deploy authenticator"
    env:
    - BINARY=dist/vault-kubernetes-authenticator
    - IMAGE=postfinance/vault-kubernetes-authenticator:${DOCKER_TAG}
    script:
    - go build -o ${BINARY} ./cmd/authenticator/main.go
    - docker build --build-arg BINARY=${BINARY} -t  -f packaging/docker/authenticator/Dockerfile
    - docker push ${IMAGE}
  - stage: build
    name: "build and deploy synchronizer"
    env:
    - BINARY=dist/vault-kubernetes-synchronizer
    - IMAGE=postfinance/vault-kubernetes-synchronizer:${DOCKER_TAG}
    script:
    - go build -o ${BINARY} ./cmd/synchronizer/main.go
    - docker build --build-arg BINARY=${BINARY} -t  -f packaging/docker/synchronizer/Dockerfile
    - docker push ${IMAGE}
  - stage: build
    name: "build and deploy token-renewer"
    env:
    - BINARY=dist/vault-kubernetes-token-renewer
    - IMAGE=postfinance/vault-kubernetes-token-renewer:${DOCKER_TAG}
    script:
    - go build -o ${BINARY} ./cmd/token-renewer/main.go
    - docker build --build-arg BINARY=${BINARY} -t  -f packaging/docker/token-renewer/Dockerfile

branches:
  only:
  - master

matrix:
  fast_finish: true
